import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Headers/Header";
import { Provider } from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`antialiased`}>
        {/* <header>
          <Header />
        </header> */}
        <main>
          {" "}
          <Provider>
            <body>{children}</body>
          </Provider>
        </main>
      </body>
    </html>
  );
}
