import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "./provider";
import Header from "@/components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`antialiased`}>
        <header>
          {/* <Provider> */}
          <Header />
          {/* </Provider> */}
        </header>
        <main>
          {" "}
          <Provider>
            <body>{children}</body>
          </Provider>
        </main>
      </body>
    </html>
  );
}
